name: PR Verify

on: [pull_request]

jobs:
  pr-verify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Install Playwright
        run: pwsh bin/Release/net9.0/playwright.ps1 install --with-deps

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
